#!/bin/bash
#
# URL: https://github.com/adriancmiranda/dotfiles
# Title: Dotfiles
# Usage: ./uninstall
# Copyright: 2016 Adrian C. Miranda
# License: N/A
# Version: 0.0.0
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
